# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151224214458 on 2016-01-07 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_word', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=100)),
                ('sentence', models.CharField(max_length=200)),
                ('meaning', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
    ]
