# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151224214458 on 2016-01-07 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game',
            field=models.CharField(default='08/01/2016', max_length=20),
            preserve_default=False,
        ),
    ]
