# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151224214458 on 2016-01-07 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0003_user_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='game',
        ),
    ]
