# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151224214458 on 2016-01-11 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0004_remove_user_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
